version: '2.1'
services:

  db-app:
    image: mysql:8
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=spike_spring_jpa_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=test123
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root123 --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 4s
      retries: 40
    volumes:
      - /data/mysql

  spring-boot-jpa-app:
    image: "drugotosto84/dockerized-spring-boot-data-jpa-spike:0.0.1-SNAPSHOT"
    container_name: jpa-app
    depends_on:
      db-app:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: "docker-compose"
