## Spring DATA SOURCE Configurations utilizzando un apposito DB su Docker e Spring application "normale"
spring:
  datasource:
    url: jdbc:mysql://192.168.99.101:3306/spike_spring_jpa_db
    username: app_user
    password: test123

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  profiles: "docker-compose"

## Spring DATA SOURCE Configurations utilizzando un apposito DB su Docker e Spring application dockerizzata
  datasource:
    url: jdbc:mysql://db-app:3306/spike_spring_jpa_db
    username: app_user
    password: test123